networks:
  app:
    driver: bridge

services:
  mongo-server:
    image: mongodb/mongodb-community-server
    ports:
      - '27017:27017'
    volumes:
      - ./docker/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-admin-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo-server:27017/
    depends_on:
      - mongo-server
      
  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile.back
    ports: 
      - 3000:3000
    environment: 
      - HTTP_PORT=3000
      - MONGO_URL=mongodb+srv://nataless:kK9ox56hIIAfxUrV@cluster0.rywwl9o.mongodb.net
      - JWT_SECRET=secret
      - JWT_EXPIRES=3d
    
    networks:
      - app

  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.front
    ports: 
      - 5173:5173
    volumes:
    
       - ./frontend:/app/src
    tty: true
    environment: 
      - VITE_MAIN_URL=http://localhost:3000/api
      - VITE_SERVER_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - app
